<Project Sdk="Microsoft.NET.Sdk">  <PropertyGroup>    <TargetFrameworks>net472;net8.0</TargetFrameworks>    <RootNamespace>Qwiq.Benchmark</RootNamespace>    <AssemblyName>Qwiq.Benchmark</AssemblyName>    <IsPackable>false</IsPackable>    <IsTestProject>false</IsTestProject>  </PropertyGroup>  <ItemGroup>    <PackageReference Include="BenchmarkDotNet" />    <PackageReference Include="MSTest.TestFramework" />  </ItemGroup>  <ItemGroup>    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" SetTargetFramework="TargetFramework=$(TargetFramework)" />    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" SetTargetFramework="TargetFramework=$(TargetFramework)" />  </ItemGroup>  </Project>