<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <RootNamespace>Qwiq.Tests.Common</RootNamespace>
    <AssemblyName>Microsoft.Qwiq.Tests.Common</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\Qwiq.Core\Extensions.cs" Link="Extensions.cs" />
    <Compile Include="..\..\src\Qwiq.Core\GenericComparer.cs" Link="GenericComparer.cs" />
  </ItemGroup>
</Project>
