// Polyfill for ArgumentNullException.ThrowIfNull for .NET Framework and .NET Standard 2.0
// Based on: https://github.com/SimonCropp/Polyfill/blob/main/src/Polyfill/ArgumentExceptions/ArgumentNullExceptionPolyfill.cs
//
// This file provides a compatibility shim for ArgumentNullException.ThrowIfNull which is only available
// in .NET 6+. For net472 and netstandard2.0 targets, we provide our own implementation using C# 14
// extension members syntax.
//
// We cannot use the Polyfill NuGet package directly due to conflicts with VSS Client polyfills.
//
// IMPORTANT: The [Embedded] attribute is applied to make this type invisible outside the current
// compilation unit. This prevents CS0121 ambiguity errors when the same polyfill file is linked
// into multiple projects that have InternalsVisibleTo relationships.
// Reference: https://andrewlock.net/behind-the-implementation-of-the-embedded-attribute-in-net-10/

// <auto-generated />
#pragma warning disable

#if !NET6_0_OR_GREATER

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

/// <summary>
/// Polyfill class providing ArgumentNullException.ThrowIfNull for older frameworks.
/// The [Embedded] attribute ensures this type is invisible to other assemblies,
/// preventing cross-assembly ambiguity when linked into multiple projects.
/// </summary>
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
static partial class Polyfill
{
    extension(ArgumentNullException)
    {
        /// <summary>Throws an <see cref="ArgumentNullException"/> if <paramref name="argument"/> is null.</summary>
        /// <param name="argument">The reference type argument to validate as non-null.</param>
        /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-10.0#system-argumentnullexception-throwifnull(system-object-system-string)
        public static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
        {
            if (argument is null)
            {
                throw new ArgumentNullException(paramName);
            }
        }
    }
}

#endif
