// Polyfill for ArgumentOutOfRangeException throw helpers for .NET Framework and .NET Standard 2.0
// Based on: https://github.com/SimonCropp/Polyfill
// We cannot use the Polyfill NuGet package directly due to conflicts with VSS Client polyfills.
//
// NOTE: The [Embedded] attribute is applied to the Polyfill class in ArgumentNullExceptionPolyfill.cs.
// Since this is a partial class, the attribute only needs to be applied once.
// Reference: https://andrewlock.net/behind-the-implementation-of-the-embedded-attribute-in-net-10/

// <auto-generated />
#pragma warning disable

#if !NET8_0_OR_GREATER

using System;
using System.Runtime.CompilerServices;

/// <summary>
/// Polyfill class providing ArgumentOutOfRangeException throw helpers for older frameworks.
/// The [Embedded] attribute is applied in ArgumentNullExceptionPolyfill.cs (partial class).
/// </summary>
static partial class Polyfill
{
    extension(ArgumentOutOfRangeException)
    {
        // Link: https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.throwifzero
        public static void ThrowIfZero(
            int value,
            [CallerArgumentExpression(nameof(value))] string? paramName = null)
        {
            if (value == 0)
            {
                throw new ArgumentOutOfRangeException(paramName, value, "Value cannot be zero.");
            }
        }

        // Link: https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.throwifequal
        public static void ThrowIfEqual<T>(
            T value,
            T other,
            [CallerArgumentExpression(nameof(value))] string? paramName = null)
            where T : IEquatable<T>?
        {
            if (EqualityComparer<T>.Default.Equals(value, other))
            {
                throw new ArgumentOutOfRangeException(paramName, value, $"Value cannot be equal to {other}.");
            }
        }

        // Link: https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.throwifnegative
        public static void ThrowIfNegative(
            int value,
            [CallerArgumentExpression(nameof(value))] string? paramName = null)
        {
            if (value < 0)
            {
                throw new ArgumentOutOfRangeException(paramName, value, "Value cannot be negative.");
            }
        }

        // Link: https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.throwifnegativeorzero
        public static void ThrowIfNegativeOrZero(
            int value,
            [CallerArgumentExpression(nameof(value))] string? paramName = null)
        {
            if (value <= 0)
            {
                throw new ArgumentOutOfRangeException(paramName, value, "Value cannot be negative or zero.");
            }
        }
    }
}

#endif
