// Polyfill for Microsoft.CodeAnalysis.EmbeddedAttribute
// This attribute marks types as "embedded" - invisible outside the current compilation.
// This prevents cross-assembly ambiguity when the same polyfill is linked into multiple projects.
//
// Based on: https://github.com/SimonCropp/Polyfill/blob/main/src/Polyfill/EmbeddedAttribute.cs
// Reference: https://andrewlock.net/behind-the-implementation-of-the-embedded-attribute-in-net-10/
//
// The [Embedded] attribute is available in Roslyn 4.14+ (.NET 10 SDK), but we need to provide
// our own definition for older compilers. When applied to a type, it makes that type invisible
// to other assemblies, even when InternalsVisibleTo is used.
//
// IMPORTANT: The AttributeUsage must allow ALL targets (AttributeTargets.All) for the compiler
// to recognize this as a valid EmbeddedAttribute. See CS9271 error for requirements.

// <auto-generated />
#pragma warning disable

#if NETFRAMEWORK || NETSTANDARD2_0

namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// Marks a type as embedded, making it invisible outside the current compilation.
    /// This prevents cross-assembly type conflicts when the same polyfill source file
    /// is linked into multiple projects.
    /// </summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.AttributeUsage(System.AttributeTargets.All, AllowMultiple = false, Inherited = false)]
    internal sealed class EmbeddedAttribute : System.Attribute
    {
    }
}

#endif
