namespace Qwiq
{
    public enum CoreField
    {
        IsDeleted = -404,
        IterationPath = -105,
        IterationId = -104,
        ExternalLinkCount = -57,
        TeamProject = -42,
        HyperlinkCount = -32,
        AttachedFileCount = -31,
        NodeName = -12,
        AreaPath = -7,
        RevisedDate = -5,
        ChangedDate = -4,
        Id = -3,
        AreaId = -2,
        AuthorizedAs = -1,
        Title = 1,
        State = 2,
        AuthorizedDate = 3,
        Watermark = 7,
        Rev = 8,
        ChangedBy = 9,
        Reason = 22,
        AssignedTo = 24,
        WorkItemType = 25,
        CreatedDate = 32,
        CreatedBy = 33,
        Description = 52,
        History = 54,
        RelatedLinkCount = 75,
        Tags = 80,
        BoardColumn = 90,
        BoardColumnDone = 91,
        BoardLane = 92,
        LinkType = 100,
    }
}